name: "pr-version-updater"
description: "Wrapper for peter-evans/create-pull-request"
inputs:
  token:
    description: "User-based personal access token"
    required: true
  chore:
    description: "Chore to use for the PR commit"
    required: true
    type: string
  tool:
    description: "Tool to reference when creating the PR"
    required: true
    type: string
  repo:
    description: "owner/repo to link to for the given release"
    required: true
    type: string
  version:
    description: "New version, without v prefix"
    required: true
    type: string
  previous_version:
    description: "Previous version, without v prefix"
    required: true
    type: string
  paths:
    description: >-
      A comma or newline-separated list of file paths to commit. Paths should
      follow git's pathspec syntax. Defaults to adding all new and modified files.
    required: true
    type: string
  base:
    description: >-
      The pull request base branch. Defaults to the branch checked out in the
      workflow.
    required: false
    type: string
  labels:
    description: "A comma or newline separated list of labels."
    required: false
    type: string
  delete-branch:
    description: >-
      Delete the branch when closing pull requests, and when undeleted after merging.
      Recommend true.
    type: boolean
    default: true
outputs: {}
runs:
  using: "composite"
  steps:
    - name: create pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.token }}
        add-paths: ${{ inputs.paths }}
        title: >-
          update ${{ inputs.tool }}
          from ${{ inputs.previous_version }}
          to ${{ inputs.version }}
        commit-message: >-
          chore(${{ inputs.chore }}): update ${{ inputs.tool }}
          from ${{ inputs.previous_version }}
          to ${{ inputs.version }}
        body: |
          Updating tool [`${{ inputs.tool }}`](https://github.com/${{ inputs.repo }}):

          - Bumping **version** from [`${{ inputs.previous_version }}`](https://github.com/${{ inputs.repo }}/releases/tag/${{ inputs.previous_version }}) to [`${{ inputs.version }}`](https://github.com/${{ inputs.repo }}/releases/tag/${{ inputs.version }}).

          Release notes: [link](https://github.com/${{ inputs.repo }}/releases/tag/${{ inputs.version }})

          Pull request auto-generated by [pr-version-updater](https://github.com/lrstanley/.github/blob/master/.github/workflows/composite-pr-version-updater/action.yml) and [meta-updaters](https://github.com/lrstanley/.github/blob/master/.github/workflows/meta-updaters.yml) action.
        signoff: true
        branch: "chore/version-updater/${{ inputs.tool }}"
        delete-branch: ${{ inputs.delete-branch }}
        base: ${{ inputs.base }}
        labels: "chore,tool-${{ inputs.tool }}${{ inputs.labels && format(',{0}', inputs.labels) }}"
        assignees: "lrstanley"
