name: ":bulb: Feature request"
description: Suggest an awesome idea for this project!
title: "feature: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for submitting a feature request! Make sure to check out the
        **discussions** section of this repository. Please also **search**
        to see if someone else has submitted a similar feature request, before
        making a new request.
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature you'd like
      description: >-
        A clear and concise description of what you want to happen, or what
        feature you'd like added.
      placeholder: 'Example: "It would be cool if X had support for Y"'
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >-
        A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]
      placeholder: >-
        Example: "I'd like to see X feature added, as I frequently have to do Y,
        and I think Z would solve that problem"
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions or features
        you've considered.
      placeholder: >-
        Example: "I've considered X and Y, however the potential problems with
        those solutions would be [...]"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Examples: logs, screenshots, etc"
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: "Please confirm the following:"
      options:
        - label: >-
            I have confirmed that someone else has not submitted a similar
            feature request.
          required: true
        - label: >-
            If implemented, this feature will help others, in addition to
            solving my problems.
          required: true
        - label: I have looked into alternative solutions to the best of my ability.
          required: true
