name: generate-readme
description: >
  A composite action to generate a README.md file. Note that only classic PATs are
  supported at this time. Required permissions:
    - contents: write

  TODO: https://github.com/cli/cli/issues/9606#issuecomment-2465580556
inputs:
  token:
    description: >-
      User-based personal access token.
    required: false
  path:
    description: >-
      The path to the README.md file.
    required: false
    default: "README.md"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event.repository.default_branch || 'master' }}
        token: ${{ inputs.token }}
    - name: generate
      continue-on-error: true
      shell: bash
      env:
        FILEPATH: ${{ inputs.path }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        ${GITHUB_ACTION_PATH}/generate.sh "$FILEPATH"
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add README.md
        git commit -m "chore(readme): auto-update [skip ci]"
        git push
