name: go-get-latest-version

on:
  workflow_call:
    outputs:
      go-version:
        description: "Latest Go version number"
        value: ${{ jobs.go-get-latest-version.outputs.go-version }}

jobs:
  go-get-latest-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.goversion.outputs.version }}
    steps:
      - id: goversion
        run: |
          echo ::set-output name=version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | sed -rn 's/.*"version": "([0-9]\.[0-9]+(\.[0-9]+)?)".*/\1/p' | head -1)
