flags:
  - "-tags=netgo,osusergo,static_build"
  - "-installsuffix=netgo"
  - "-trimpath"
ldflags:
  - "-s"
  - "-w"
  - "-X main.version={{.Version}}"
  - "-X main.commit={{.Commit}}"
  - "-X main.date={{.CommitDate}}"
  - "-X main.builtBy=github-actions"
  - "-extldflags=-static"
env:
  - CGO_ENABLED=0
mod_timestamp: "{{ .CommitTimestamp }}"
hooks:
  post: sh -c "upx --best --lzma \"{{ .Path }}\" || /bin/true"
targets:
  - linux_amd64
  - linux_arm64
  - linux_arm
  - freebsd_amd64
  - windows_amd64
  - darwin_amd64
