# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
builds:
  - dir: .
    main: .

archives:
  - id: archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
  - id: binary
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

release:
  draft: false
  prerelease: auto
  mode: replace
  disable: false
  extra_files:
    - glob: LICENSE

changelog:
  skip: false
  use: github
  groups:
    - title: ":warning: Breaking Changes :warning:"
      regexp: "(?i).*breaking.*"
      order: 0
    - title: ":sparkles: New Features"
      regexp: "(?i)(^add|^feat|.*feature.*|.*support .*)"
      order: 1
    - title: ":lady_beetle: Bug Fixes"
      regexp: "(?i)(^fix|.*fixes.*|.*resolv.*|.*issue.*)"
      order: 2
    - title: ":broom: Misc"
      order: 999
  filters:
    exclude:
      - "(?i)(^docs?:)"
      - "(?i)(\\[skip ci\\]|\\[ci skip\\])"
      - "(?i)auto-applied|auto-update"
      - "(?i)typo|spelling"
      - "(?i)(^\\.|^fix$|^test$|^testing$|^ignore|^ok\\s+)"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

milestones:
  - close: true
    fail_on_error: false
    name_template: "{{ .Tag }}"
