name: docker-release

on:
  workflow_call:
    inputs:
      name:
        description: >
          Name used for the built image (e.g. foo would result in
          ghcr.io/user/foo).
        required: false
        type: string
      dockerfile:
        description: "Alternative dockerfile location."
        required: false
        type: string
        default: Dockerfile
      workdir:
        description: >
          Use when you want to change directories before invoking commands.
        required: false
        type: string
      context:
        description: "Use when you want to change the docker context."
        required: false
        type: string
      buildoptions:
        description: >
          Use buildoptions when you want to pass build arguments (e.g.
          --build-arg, --force-rm, etc).
        required: false
        type: string

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --force --tags
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - id: generate-tags
        run: ./ghmeta/scripts/generate-docker-tags.sh
        env:
          GIT_SHA: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_REF_TYPE: ${{ github.ref_type }}
          EVENT_NAME: ${{ github.event_name }}
          PR_ID: ${{ github.event.pull_request.number }}
      - name: build-and-push
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: ${{ github.repository_owner }}/${{ inputs.name || github.event.repository.name }}
          tags: ${{ steps.generate-tags.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ${{ inputs.dockerfile }}
          workdir: ${{ inputs.workdir }}
          context: ${{ inputs.context }}
          buildoptions:
            --label="org.opencontainers.image.title=${{ github.repository_owner }}/${{ inputs.name || github.event.repository.name }}" \
            --label="org.opencontainers.image.name=${{ inputs.name || github.event.repository.name }}" \
            --label="org.opencontainers.image.description=${{ github.event.repository.description || 'n/a' }}" \
            --label="org.opencontainers.image.created=${{ github.event.head_commit.timestamp || 'unknown' }}" \
            --label="org.opencontainers.image.authors=${{ github.event.repository.owner.name }} <${{ github.event.repository.owner.email || 'unknown' }}>" \
            --label="org.opencontainers.image.license=MIT" \
            --label="org.opencontainers.image.revision=${{ github.event.head_commit.id || 'unknown' }}" \
            --label="org.opencontainers.image.version=${{ steps.generate-tags.outputs.version || 'unknown' }}" \
            --label="org.opencontainers.image.source=${{ github.event.repository.url || 'unknown' }}" ${{ inputs.buildoptions }} \
