name: docker-release

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        description: "Snyk token for vulnerability scanning."
        required: false
    inputs:
      name:
        description: >
          Name used for the built image (e.g. foo would result in
          ghcr.io/user/foo).
        required: false
        type: string
      dockerfile:
        description: "Alternative dockerfile location."
        required: false
        type: string
        default: Dockerfile
      context:
        description: "Use when you want to change the docker context."
        required: false
        type: string
        default: "."
      push:
        description: "If images should be pushed (not just built and scanned)."
        required: false
        type: boolean
        default: true
      scan:
        description: "If images should be security/quality/etc scanned."
        required: false
        type: boolean
        default: true

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      checks: write
      contents: read
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: git fetch --force --tags
      - name: get-latest-tag
        id: get-latest-tag
        run: |
          LATEST=$(git tag --sort=-v:refname | egrep "^v?[0-9]+\.[0-9]+\.[0-9]+$" | head -1)
          echo "version=${LATEST}" >> "$GITHUB_OUTPUT"
      - name: docker-buildx-setup
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3
      - name: docker-login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: fetch-metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.name || github.event.repository.name }}
          flavor: |
            latest=false
          tags: |
            type=raw,priority=1000,value=latest,enable=${{ github.ref_name == steps.get-latest-tag.outputs.version || !steps.get-latest-tag.outputs.version }}
            type=semver,pattern={{version}}
            type=semver,priority=600,pattern={{major}},enable=${{ github.ref_name == steps.get-latest-tag.outputs.version || !steps.get-latest-tag.outputs.version }}
            type=semver,priority=500,pattern={{major}}.{{minor}}
            type=semver,priority=800,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,priority=700,pattern={{major}}.{{minor}}.{{patch}},suffix=-{{date 'YYYYMMDD'}}-{{sha}},enable=${{ github.ref_name == steps.get-latest-tag.outputs.version || !steps.get-latest-tag.outputs.version }}
            type=ref,priority=900,event=branch
            type=ref,event=pr
          labels: |
            org.opencontainers.image.license=MIT
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.authors=${{ github.event.repository.owner.name }} <${{ github.event.repository.owner.email || 'unknown' }}>
            org.opencontainers.image.name=${{ inputs.name || github.event.repository.name }}
      - name: docker-build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: ${{ inputs.context }}
          load: true
          tags: tmp
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: scan-snyk-docker
        if: github.event_name != 'pull_request' && inputs.scan
        continue-on-error: true
        uses: snyk/actions/docker@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: tmp
          args: --file=${{ inputs.dockerfile }}
      - name: Upload result to GitHub Code Scanning
        if: github.event_name != 'pull_request' && inputs.scan
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169 # v3
        with:
          sarif_file: snyk.sarif
          wait-for-processing: true
      - name: docker-tag-and-push
        if: inputs.push
        run: |
          echo -e "${{ steps.meta.outputs.tags }}" | while read -r tag;do
            (
              set -x
              docker tag tmp "$tag"
              docker push "$tag"
            )
          done
