# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: docker-prune

on:
  workflow_call:
    inputs:
      names:
        description: Comma-separated list of images that should be pruned.
        required: false
        type: string
      remove-after:
        description: >
          How old package versions must be before deletion (humantime, e.g. 1w, 30d, 5h).
          Passed to snok/container-retention-policy cut-off.
        required: false
        type: string
    secrets:
      token:
        description: >
          A Github Personal Access Token. Must be one generated outside of
          Actions, as current Actions PAT's don't allow deleting packages.
        required: false

jobs:
  docker-prune:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write
    steps:
      - name: prune untagged
        continue-on-error: true
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.token || secrets.USER_PAT }}
          image-names: ${{ inputs.names || github.event.repository.name }}
          cut-off: ${{ inputs.remove-after || '1w' }}
          timestamp-to-use: updated_at
          tag-selection: untagged
      - name: prune pr-* tags
        continue-on-error: true
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.token || secrets.USER_PAT }}
          image-names: ${{ inputs.names || github.event.repository.name }}
          cut-off: ${{ inputs.remove-after || '30d' }}
          timestamp-to-use: updated_at
          tag-selection: tagged
          image-tags: "pr-*"
      - name: prune alpha/rc tags
        continue-on-error: true
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.token || secrets.USER_PAT }}
          image-names: ${{ inputs.names || github.event.repository.name }}
          cut-off: ${{ inputs.remove-after || '30d' }}
          timestamp-to-use: updated_at
          tag-selection: tagged
          image-tags: "*-alpha.* *-rc.*"
