name: label-issue-comments

on: [workflow_call]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            stale
            waiting-reply
