# USAGE:
#   jobs:
#     node-test:
#       uses: lrstanley/.github/.github/workflows/lang-node-test.yml@master
#       with:
#         node-version: 1.2.3

name: node-test

on:
  workflow_call:
    inputs:
      node-version:
        description: >
          Node version .
        required: true
        type: string
      node-package-manager:
        description: >
          Node package manager (npm/yarn/pnpm/etc).
        required: false
        type: string
        default: "npm"

jobs:
  make:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v3
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - name: install-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: pnpm install
        if: inputs.node-package-manager == 'pnpm'
        uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
        id: pnpm-install
        with:
          version: latest
          run_install: false
      - name: node-test
        id: node-test
        run: |
          ./ghmeta/scripts/make.sh node-prepare
          ./ghmeta/scripts/make.sh node-test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ${{ steps.node-test.outputs.output }}
          if-no-files-found: warn
          retention-days: 5
