# USAGE:
#   jobs:
#     node-test:
#       uses: lrstanley/.github/.github/workflows/lang-node-test.yml@master
#       with:
#         node-version: 1.2.3

name: node-test

on:
  workflow_call:
    inputs:
      node-version:
        description: >
          Node version to use.
        required: false
        type: string
        default: "lts/*"
jobs:
  make:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v5
      - uses: lrstanley/.github/composite/install-node@master
        with:
          version: ${{ inputs.node-version }}
      - uses: lrstanley/.github/composite/invoke-task@master
        with:
          task: node-prepare,prepare
          allow-undefined: true
      - uses: lrstanley/.github/composite/invoke-task@master
        with:
          task: node-test,test
          allow-undefined: false
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ${{ steps.node-test.outputs.output }}
          if-no-files-found: warn
          retention-days: 5
