name: go-test-matrix

on:
  workflow_call:
    inputs:
      num-versions:
        required: true
        type: number

# TODO: permissions
jobs:
  go-get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.fetch-versions.outputs.versions }}
    steps:
      - id: fetch-versions
        run: |
          VERSIONS=$(
            curl -sSL https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json \
              | jq -rc '"\"\(.[].version)\""' | awk -F. '!seen[$1, $2]++' \
              | head -n ${{ inputs.num-versions }} | jq -sc
          )
          echo ::set-output name=versions::${VERSIONS}
  go-test-matrix:
    runs-on: ubuntu-latest
    needs: [go-get-versions]
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.go-get-versions.outputs.versions) }}
    steps:
      - uses: actions/setup-go@v3
        with: { go-version: "${{ matrix.go-version }}" }
      - uses: actions/checkout@v3
      - run: |
          GORACE="exitcode=1 halt_on_error=1" go test -v -race -timeout 3m -count 3 -cpu 1,4
