# USAGE:
#   jobs:
#     go-version:
#       uses: lrstanley/.github/.github/workflows/lang-go-latest-version.yml@master
#     go-lint:
#       needs: [go-version]
#       uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
#       with:
#         go-version: ${{ needs.go-version.outputs.version }}

name: go-lint

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      cache-key: # use when testing against multiple go versions, for example.
        required: false
        type: string

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with: { go-version: "${{ inputs.go-version }}" }
      - uses: actions/checkout@v3
      - run: |
          go test -v -coverprofile=coverage.txt -timeout 3m
          bash <(curl -s https://codecov.io/bash)
      - run: go vet .
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: latest
          install-go: false
          cache-key: "${{ inputs.cache-key }}"
