name: go-test-matrix

# logic:
#   given: 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3
#
#   minor: 1, patch: 1, returns: 1.3.3
#   minor: 2, patch: 1, returns: 1.3.3, 1.2.5
#   minor: 1, patch: 2, returns: 1.3.2, 1.3.3
#   minor: 2, patch: 2, returns: 1.3.3, 1.3.2, 1.2.5, 1.2.4

on:
  workflow_call:
    inputs:
      go-version:
        description: >
          Go version if only a specific version is desired (overrides
          minor/patch).
        required: false
        type: string
      node-version:
        description: >
          Node version (e.g. to build frontends).
        required: false
        type: string
      node-package-manager:
        description: >
          Node package manager (npm/yarn/pnpm/etc).
        required: false
        type: string
        default: "npm"
      node-package-manager-lock:
        description: >
          Node package manager lock file (npm/yarn/pnpm/etc).
        required: false
        type: string
        default: "**/package-lock.json"
      num-minor:
        description: "Number of minor semver versions of Go to use"
        required: false
        type: number
        default: 2
      num-patch:
        description: "Number of patch semver versions of Go to use"
        required: false
        type: number
        default: 1
      run:
        description: >
          Alternative command to run, instead of the builtin testing
          command.
        required: False
        type: string

jobs:
  go-versions:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      versions: ${{ steps.fetch-versions.outputs.versions }}
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - id: fetch-versions
        run: ./ghmeta/scripts/versions-go.sh ${{ inputs.go-version || 'many' }}
        env:
          NUM_MINOR: ${{ inputs.num-minor }}
          NUM_PATCH: ${{ inputs.num-patch }}
  go-test-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [go-versions]
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v3
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: install-go
        uses: actions/setup-go@v3
        with: { go-version: "${{ matrix.go-version }}" }
      - name: install pnpm
        if: inputs.node-package-manager == 'pnpm'
        uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d
        id: pnpm-install
        with:
          version: latest
          run_install: false
      - name: install-node
        if: inputs.node-version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-package-manager }}
          cache-dependency-path: ${{ inputs.node-package-manager-lock }}
      - name: custom-go-test
        if: inputs.run
        run: ${{ inputs.run }}
      - name: standard-go-test
        if: ${{ !inputs.run }}
        run: |
          ./ghmeta/scripts/make.sh go-prepage prepare
          ./ghmeta/scripts/make.sh go-test test || GORACE="exitcode=1 halt_on_error=1" go test -v -race -timeout 3m -count 3 -cpu 1,4 ./...
