# USAGE:
#   jobs:
#     go-version:
#       uses: lrstanley/.github/.github/workflows/lang-go-latest-version.yml@master
#     some-other-job:
#       needs: [go-version]
#       uses: ...
#       with:
#         go-version: ${{ needs.go-version.outputs.version }}

name: go-get-latest-version

on:
  workflow_call:
    outputs:
      go-version:
        description: "Latest Go version number"
        value: ${{ jobs.go-get-latest-version.outputs.go-version }}

jobs:
  go-get-latest-version:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      go-version: ${{ steps.goversion.outputs.version }}
    steps:
      - id: goversion
        run: |
          VERSION=$(
              curl -sSL https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json \
                  | jq -r '[.[] | select(.stable == true)][0].version'
          )
          echo ::set-output name=version::${VERSION}
