# USAGE:
#   jobs:
#     go-release:
#       needs: [go-version]
#       uses: lrstanley/.github/.github/workflows/lang-go-release.yml@master
#       with:
#         go-version: 1.2.3 # or don't provide to use latest Go version.

name: go-release

on:
  workflow_call:
    inputs:
      go-version:
        description: >
          Go version to use for linting -- defaults to the latest stable Go
          version.
        required: false
        type: string
      has-ghcr:
        description: "If GHCR packages exist for this project."
        required: false
        type: boolean
        default: false
      image-name:
        description: >
          If 'has-ghcr' is enabled, this will be the image name referenced.
        required: false
        type: string
      archives:
        description: >
          If archives, rather than just direct binaries, should be used.
        required: false
        type: boolean
        default: false
      draft:
        description: >
          If the release (if publishing) should be marked as a draft.
        required: false
        type: boolean
        default: false
      upload-artifacts:
        description: >
          If artifacts should be uploaded via GH Actions artifacts (for
          snapshot only).
        required: false
        type: boolean
        default: true

jobs:
  go-release:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      discussions: write
      packages: write
      pages: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - name: git-clone-tools-repo
        if: ${{ !inputs.go-version }}
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - id: goversion
        if: ${{ !inputs.go-version }}
        run: ./ghmeta/scripts/versions-go.sh ${{ inputs.go-version || 'latest' }}
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ inputs.go-version || steps.goversion.outputs.version }}"
      - run: ./ghmeta/scripts/goreleaser.sh
        env:
          INPUT_HAS_GHCR: ${{ inputs.has-ghcr }}
          INPUT_IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.name || github.event.repository.name }}
          INPUT_ARCHIVES: ${{ inputs.archives }}
          INPUT_DRAFT: ${{ inputs.draft }}
          INPUT_PR_ID: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload-snapshot-binaries
        if: ${{ inputs.upload-artifacts && github.ref_type != 'tag' }}
        uses: actions/upload-artifact@v3
        with:
          name: snapshot-binaries
          retention-days: 14
          path: dist/**
