# USAGE:
#   jobs:
#     go-release:
#       needs: [go-version]
#       uses: lrstanley/.github/.github/workflows/lang-go-release.yml@master
#       with:
#         go-version: 1.2.3 # or don't provide to use latest Go version.

name: go-release

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version to use for linting -- defaults to the latest stable Go version."
        required: false
        type: string
      has-ghcr:
        description: "If GHCR packages exist for this project"
        required: false
        type: boolean
        default: false
      image-name:
        description: "If 'has-ghcr' is enabled, this will be the image name referenced."
        required: false
        type: string
      upload-artifacts:
        description: "If artifacts should be uploaded via GH Actions artifacts (for snapshot only)."
        required: false
        type: boolean
        default: true

jobs:
  go-release:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - name: git-clone-tools-repo
        if: ${{ !inputs.go-version }}
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - id: goversion
        if: ${{ !inputs.go-version }}
        run: ./ghmeta/scripts/versions-go.sh ${{ inputs.go-version || 'latest' }}
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ inputs.go-version || steps.goversion.outputs.version }}"
      - run: ./ghmeta/scripts/goreleaser.sh
        env:
          GIT_SHA: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_REF_TYPE: ${{ github.ref_type }}
          EVENT_NAME: ${{ github.event_name }}
          PR_ID: ${{ github.event.pull_request.number }}
