# USAGE:
#   jobs:
#     node-test:
#       uses: lrstanley/.github/.github/workflows/lang-node-test.yml@master
#       with:
#         node-version: 1.2.3

name: node-test

on:
  workflow_call:
    inputs:
      node-version:
        description: >
          Node version .
        required: true
        type: string

jobs:
  make:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
      - name: git-clone-tools-repo
        uses: actions/checkout@v4
        with:
          repository: lrstanley/.github
          path: ghmeta
      - name: install-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: check if pnpm is used
        id: uses-pnpm
        run: echo "uses-pnpm=$(find . -mindepth 1 -maxdepth 6 -type f -name pnpm-lock.yaml | grep -q . && echo true || echo false)" >> "$GITHUB_OUTPUT"
      - name: pnpm install
        if: steps.uses-pnpm.outputs.uses-pnpm == 'true'
        uses: pnpm/action-setup@v4.1.0
        id: pnpm-install
        with:
          version: latest
          run_install: false
      - name: node-test
        id: node-test
        run: |
          set +e

          ./ghmeta/scripts/make.sh node-prepare prepare
          RESULTS="$?"
          if [ "$?" -gt 0 ] && [ "$?" -ne 127 ];then exit "$RESULTS";fi

          ./ghmeta/scripts/make.sh node-test test
          RESULTS="$?"
          if [ "$RESULTS" -ne 127 ];then exit "$RESULTS";fi

          exit 0
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ${{ steps.node-test.outputs.output }}
          if-no-files-found: warn
          retention-days: 5
