# USAGE:
#   jobs:
#     go-lint:
#       needs: [go-version]
#       uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
#       with:
#         go-version: 1.2.3 # or don't provide to use latest Go version.

name: go-lint

on:
  workflow_call:
    inputs:
      go-version:
        description: >
          Go version to use for linting -- defaults to the latest stable Go
          version.
        required: false
        type: string
      staticcheck:
        description: "Enables linting with staticcheck."
        default: True
        required: False
        type: boolean
      govet:
        description: "Enables linting with go vet."
        default: True
        required: False
        type: boolean
      codecov:
        description: >
          Enables Codecov integration (requires running tests at least once).
        default: True
        required: False
        type: boolean

# TODO: permissions
jobs:
  go-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - id: fetch-versions
        run: ./ghmeta/scripts/versions-go.sh ${{ inputs.go-version || "latest" }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.fetch-versions.outputs.version }}
      - name: codecov
        if: inputs.codecov
        run: |
          ./ghmeta/scripts/install-codecov.sh

          go test -v -coverprofile=coverage.txt -timeout 3m ./...
          codecov -f coverage.txt
      - name: govet
        if: inputs.govet
        run: go vet -composites=false ./...
      - name: staticcheck
        if: inputs.staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -f stylish ./...
