# USAGE:
#   jobs:
#     go-version:
#       uses: lrstanley/.github/.github/workflows/lang-go-latest-version.yml@master
#     some-other-job:
#       needs: [go-version]
#       uses: ...
#       with:
#         go-version: ${{ needs.go-version.outputs.version }}

name: go-get-latest-version

on:
  workflow_call:
    outputs:
      version:
        description: "Latest Go version number"
        value: ${{ jobs.go-get-latest-version.outputs.version }}

jobs:
  go-get-latest-version:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      version: ${{ steps.goversion.outputs.version }}
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v4
        with:
          repository: lrstanley/.github
      - id: goversion
        run: ./scripts/versions-go.sh latest
