name: meta-terraform

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  trigger-run:
    runs-on: ubuntu-latest
    steps:
      - env:
          TF_WORKSPACE: ws-gAVzwxnWWbUvW7ez
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          cat <<EOF >> playload.json
          {
            "data": {
              "attributes": {
                "message": "scheduled-run"
              },
              "type":"runs",
              "relationships": {
                "workspace": {
                  "data": {
                    "type": "workspaces",
                    "id": "${TF_WORKSPACE}"
                  }
                }
              }
            }
          }
          EOF
          curl \
            --header "Authorization: Bearer ${TF_API_TOKEN}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data @payload.json \
            https://app.terraform.io/api/v2/runs
