name: meta-terraform

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  trigger-run:
    runs-on: ubuntu-latest
    steps:
      - env:
          TF_WORKSPACES: |
            ws-gAVzwxnWWbUvW7ez
            ws-NEZnyEP8C6TqdZqS
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          for ID in $TF_WORKSPACES;do
            cat <<EOF > payload.json
            {
              "data": {
                "attributes": {
                  "message": "scheduled-run"
                },
                "type":"runs",
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "${ID}"
                    }
                  }
                }
              }
            }
            EOF
            curl -sS \
              --header "Authorization: Bearer ${TF_API_TOKEN}" \
              --header "Content-Type: application/vnd.api+json" \
              --request POST \
              --data @payload.json \
              https://app.terraform.io/api/v2/runs | jq '.'
