name: meta-secret-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: filter-repositories
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SECRET_SYNC_PAT }}
          script: |
            const query = `
              query {
                viewer {
                  repositories(first: 100, isFork: false, isLocked: false, ownerAffiliations: [OWNER]) {
                    nodes {
                      isArchived
                      isDisabled
                      isMirror
                      isTemplate
                      isUserConfigurationRepository
                      nameWithOwner
                    }
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                  }
                }
              }
            `;
            const result = await github.graphql(query)
            const repos = result.viewer.repositories.nodes.filter(repo => {
              return (
                !repo.isArchived &&
                !repo.isDisabled &&
                !repo.isMirror &&
                !repo.isTemplate &&
                !repo.isUserConfigurationRepository &&
                !repo.nameWithOwner.endsWith("/.github")
              )
            }).map(repo => repo.nameWithOwner)
            console.log(repos)
            core.setOutput("results", JSON.stringify(repos))
      - run: echo "${{ steps.filter-repositories.outputs.results }}"
      - uses: google/secrets-sync-action@v1.7.0
        with:
          SECRETS: |
            ^USER_PAT$
            ^SNYK.*
          REPOSITORIES: |
            ${{github.repository}}
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.SECRET_SYNC_PAT }}
