name: renovate

on:
  workflow_call:
    secrets:
      app-id:
        description: >-
          GitHub App ID.
        required: false
      app-private-key:
        description: >-
          GitHub App private key.
        required: false
    inputs:
      dry-run:
        description: >-
          Run renovate in dry-run mode (no changes will be made).
        required: false
        type: boolean
        default: false
      log-level:
        description: >-
          Log level for renovate (debug, info, warn, error, fatal).
        required: false
        type: string
        default: "info"
      cache:
        description: >-
          Enable/disable cache.
        type: boolean
        default: true
      force-run:
        description: >-
          Force running now regardless of schedule.
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  LOG_LEVEL: "${{ inputs.log-level }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dry-run == true }}"
  RENOVATE_REPOSITORY_CACHE: ${{ inputs.cache == true && 'enabled' || 'disabled' }}
  RENOVATE_REPOSITORY_CACHE_TYPE: local
  RENOVATE_PRESET_CACHE_PERSISTENCE: ${{ inputs.cache == true && 'true' || 'false' }}
  RENOVATE_CACHE_DIR: /tmp/renovate/cache/repository

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.app-id || secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.app-private-key || secrets.BOT_PRIVATE_KEY }}"
      - uses: actions/checkout@v5
        with:
          repository: lrstanley/.github
      - name: toggle-force-run
        if: ${{ inputs.force-run == true }}
        run: |
          sed -ri 's:on friday:at any time:g' renovate/main.json5
      - uses: actions/cache@v4
        if: ${{ inputs.cache == true }}
        with:
          key: renovate-${{ runner.os }}
          path: /tmp/renovate/cache
      - run: |
          if [ -d /tmp/renovate ]; then
            sudo chown -R 12021:0 /tmp/renovate
          fi
      - uses: renovatebot/github-action@v43.0.7
        with:
          configurationFile: renovate/main.json5
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "41"
