# USAGE:
#   jobs:
#     tag-semver:
#       uses: lrstanley/.github/.github/workflows/tag-semver.yml@master
#       with: { method: "", ref: "", custom: "" }

name: tag-semver

on:
  workflow_call:
    inputs:
      method: # major, minor, patch, alpha, rc, custom
        description: "Tagging method to use"
        required: true
        type: string
      custom:
        description: >
          Custom tag, if the default doesn't suffice. Must also use method
          'custom'.
        required: false
        type: string
      ref:
        description: "Git ref to apply tag to"
        required: false
        type: string
    secrets:
      token:
        description: >
          A Github Personal Access Token. Must be one generated outside of
          Actions if you want this workflow to trigger other workflows
          (standard action tokens are unable to make events that trigger
          other workflows).
        required: true

jobs:
  tag-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.token }}
      - run: git fetch --force --tags
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
          path: ghmeta
      - run: ./ghmeta/scripts/generate-semver-tag.sh
        env:
          METHOD: ${{ inputs.method }}
          CUSTOM: ${{ inputs.custom }}
