name: triage

on:
  workflow_call:
    secrets:
      token:
        description: "User-based personal access token, used if you want dependabot PR's to be auto-merged."
        required: false

jobs:
  issues:
    if: >-
      (github.event_name == 'issues' || github.event_name == 'issue_comment')
      && !github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v4
        with:
          repository: lrstanley/.github
      - name: label-issues
        if: >-
          github.event_name == 'issues'
          && (github.event.action == 'opened' || github.event.action == 'edited')
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: triage/label-issues.yml
          enable-versioned-regex: 0
      - name: remove-labels
        if: github.event_name == 'issue_comment'
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        with:
          labels: |
            stale
            waiting-reply
  pull-requests:
    if: >-
      github.event_name == 'pull_request_target'
      || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v4
        with:
          repository: lrstanley/.github
      - name: label-pull-requests
        if: github.event_name == 'pull_request_target'
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          configuration-path: triage/label-pull-requests.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: label-pull-requests-sizes
        if: github.event_name == 'pull_request_target'
        uses: codelytv/pr-size-labeler@c7a55a022747628b50f3eb5bf863b9e796b8f274
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "30"
          s_max_size: "60"
          m_max_size: "150"
          l_max_size: "300"
          message_if_xl: ""
          files_to_ignore: >-
            package-lock.json
            Pipefile.lock
            go.sum
            .terraform.lock.hcl
