name: label-issues

on: [workflow_call]

jobs:
  issue_triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
      - uses: github/issue-labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: configs/triage/label-issues.yml
