name: triage

on:
  workflow_call:
    secrets:
      token:
        description: "User-based personal access token, used if you want dependabot PR's to be auto-merged."
        required: false

jobs:
  issues:
    if: >-
      (github.event_name == 'issues' || github.event_name == 'issue_comment')
      && !github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v4
        with:
          repository: lrstanley/.github
      - name: label-issues
        if: >-
          github.event_name == 'issues'
          && (github.event.action == 'opened' || github.event.action == 'edited')
        uses: github/issue-labeler@6bea9ed491bb74fce38775b3d863e64a59dbd9eb
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: triage/label-issues.yml
          enable-versioned-regex: 0
      - name: remove-labels
        if: github.event_name == 'issue_comment'
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        with:
          labels: |
            stale
            waiting-reply
  pull-requests:
    if: >-
      github.event_name == 'pull_request_target'
      || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v4
        with:
          repository: lrstanley/.github
      # - name: dependabot-auto-merge
      #   if: github.event_name == 'pull_request_target'
      #   continue-on-error: true
      #   uses: ahmadnassri/action-dependabot-auto-merge@5d98f10d910782d0bb431fc03ae26532543ae184
      #   with:
      #     config: triage/dependabot-auto-merge.yml
      #     github-token: ${{ secrets.token }}
      - name: label-pull-requests
        if: github.event_name == 'pull_request_target'
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          configuration-path: triage/label-pull-requests.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: label-pull-requests-sizes
        if: github.event_name == 'pull_request_target'
        uses: codelytv/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "30"
          s_max_size: "60"
          m_max_size: "150"
          l_max_size: "300"
          message_if_xl: ""
          files_to_ignore: >-
            package-lock.json
            Pipefile.lock
            go.sum
            .terraform.lock.hcl
