name: triage

on: [workflow_call]

jobs:
  issues:
    if: >-
      (github.event_name == 'issues' || github.event_name == 'issue_comment')
      && !github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
      - name: label-issues
        if: >-
          github.event_name == 'issues'
          && (github.event.action == 'opened' || github.event.action == 'edited')
        uses: github/issue-labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: triage/label-issues.yml
      - name: remove-labels
        if: github.event_name == 'issue_comment'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            stale
            waiting-reply
  pull-requests:
    if: >-
      (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
      || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: git-clone-tools-repo
        uses: actions/checkout@v3
        with:
          repository: lrstanley/.github
      - name: dependabot-auto-merge
        if: github.event_name == 'pull_request'
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          config: triage/dependabot-auto-merge.yml
      - name: label-pull-requests
        if: github.event_name == 'pull_request_target'
        uses: actions/labeler@v4
        with:
          configuration-path: triage/label-pull-requests.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: label-pull-requests-sizes
        if: github.event_name == 'pull_request'
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: "30"
          s_max_size: "60"
          m_max_size: "150"
          l_max_size: "300"
          message_if_xl: ""
          files_to_ignore: >-
            package-lock.json
            Pipefile.lock
            go.sum
            .terraform.lock.hcl
